services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - local.env
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: pgvector/pgvector:pg15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=affiliate_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
